### PR TITLE
Block Exporter #4: Exporter Div Formatting

### PR DESCRIPTION
**Pull request by quachtina96**
Before: Block Library peeked out from below while on the Block Exporter Tab
screen shot 2016-08-02 at 4 23 01 pm

After:
screen shot 2016-08-02 at 4 24 54 pm
### block_exporter_tools.js
- properly hides the hidden workspace --before, you could see the edge of it at the bottom on the block factory tab.

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/17)

### CODE REVIEW

**Comment by quachtina96** [comment]
@vicng @picklesrus @evd2014 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/17#-:-KOCbgFC74zr_IZrqxFn:-1171593519)_

**Comment by edauterman** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/17#-:-KOCcMFzoEXGcaqv9cNd:1417088721)_

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/17#-:-KOCnxm5GzZQVEFkxPsk:1417088721)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/17#-:-KODCpxn3F77HNc55bVe:1417088721)_

**Pull request merged**
