### PR TITLE
Block Exporter: 'Add All Stored Blocks' button for export, Prefer JSON

### PR DESCRIPTION
**Pull request by quachtina96**
## Overview

User can select all blocks in block library for export and deselect blocks from there. This saves users time because they won't need to select every block by hand.
screen shot 2016-08-05 at 10 53 16 am
Prefer JSON as a language format because it has more cross-platform compatibility than JavaScript.
screen shot 2016-08-05 at 10 56 37 am
screen shot 2016-08-05 at 10 56 45 am
### app_controller.js
- added 'Add All Stored Blocks' Button click handler
### block_exporter_controller.js
- added addAllBlocksToWorkspace function
### block_exporter_tools.js
- made addBlockDefinitions public so I could use it in block exporter controller.
### block_exporter_view.js
- added functions to add blocks to selector workspace and to clean up the workspace
### index.html
- added 'Add All Stored Blocks' button
- in selectors for block definition language format, prefer JSON

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/24)

### CODE REVIEW

**Comment by quachtina96** [comment]
@vicng @evd2014 @picklesrus 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/24#-:-KOQvioHX9qy_xiiy9HP:b-6pcjjx)_

**Comment by picklesrus** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[demos/blockfactoryv2/block_exporter_view.js, line 96 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/24#-KOR3T5Ms38hPppvM5dT:-KOR3T5Ms38hPppvM5dU:bgkzl8k) ([raw file](https://github.com/quachtina96/blockly/blob/cf8c0b1a1361253b095ac811e2cb34ec0835b981/demos/blockfactoryv2/block_exporter_view.js#L96)):_

> ``` JavaScript
>  * @param {string} blockType - Type of block to select.
>  */
> BlockExporterView.prototype.selectBlock = function(blockType) {
> ```

should this be called selectBlock?  Seems more like it is adding them then marking them selected.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/24)_

**Comment by quachtina96** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[demos/blockfactoryv2/block_exporter_view.js, line 96 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/24#-KOR3T5Ms38hPppvM5dT:-KOR70KlHHo0EF3UG-xL:bjnr2zv) ([raw file](https://github.com/quachtina96/blockly/blob/cf8c0b1a1361253b095ac811e2cb34ec0835b981/demos/blockfactoryv2/block_exporter_view.js#L96)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> should this be called selectBlock?  Seems more like it is adding them then marking them selected.
> </details>
> You're right--in terms of the Block Exporter, adding a block to the selector workspace is selecting it, but for the function it makes more sense to call it addBlock. Done!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/24)_

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/24#-:-KOfIl695FwHw-9BhQiF:bnfp4nl)_

**Comment by edauterman** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/24#-:-KOg3XcG_-u1Lif1yT6q:bnfp4nl)_

**Comment by vicng** [comment]
:lgtm: after minor fixes.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[demos/blockfactoryv2/app_controller.js, line 127 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/24#-KOgAN1GnpcxJsYsNdkp:-KOgAN1HN19yFlpZ9dza:bogfa64) ([raw file](https://github.com/quachtina96/blockly/blob/a8dab7cfc6055c72a282e82db2947e73d63b502c/demos/blockfactoryv2/app_controller.js#L127)):_

> ``` JavaScript
>         self.exporter.clearSelectedBlocks();
>       });
>   document.getElementById('selectAllButton').addEventListener('click',
> ```

Fix button name id.

---

_[demos/blockfactoryv2/block_exporter_view.js, line 112 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/24#-KOgAVwV9i-k1jvbFFIY:-KOgAVwV9i-k1jvbFFIZ:b-k4d6uj) ([raw file](https://github.com/quachtina96/blockly/blob/a8dab7cfc6055c72a282e82db2947e73d63b502c/demos/blockfactoryv2/block_exporter_view.js#L112)):_

> ``` JavaScript
>  * Neatly layout the blocks in selector workspace.
>  */
> BlockExporterView.prototype.cleanSelectorWorkspace = function() {
> ```

Rename this cleanUpSelectorWorkspace(). It's just too similar to clearSelectorWorkspace().

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/24#-:-KOgBJHo8kB6fJ24vWTW:bo3h749)_

**Comment by quachtina96** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[demos/blockfactoryv2/app_controller.js, line 127 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/24#-KOgAN1GnpcxJsYsNdkp:-KOgJhpVkiRst-yHO_Lm:b-896fix) ([raw file](https://github.com/quachtina96/blockly/blob/a8dab7cfc6055c72a282e82db2947e73d63b502c/demos/blockfactoryv2/app_controller.js#L127)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Fix button name id.
> </details>
> Done.

---

_[demos/blockfactoryv2/block_exporter_view.js, line 112 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/24#-KOgAVwV9i-k1jvbFFIY:-KOgJbfR8MerCoL5sbPS:b-896fix) ([raw file](https://github.com/quachtina96/blockly/blob/a8dab7cfc6055c72a282e82db2947e73d63b502c/demos/blockfactoryv2/block_exporter_view.js#L112)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Rename this cleanUpSelectorWorkspace(). It's just too similar to clearSelectorWorkspace().
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/24)_

**Pull request merged**
