### PR TITLE
Block Library Export  #2: Exporter UI, Tabs, Export Settings

### PR DESCRIPTION
**Pull request by quachtina96**
- added the Block Library Exporter div to contain the exporter UI, which includes an Export Settings form and a div in which to inject a workspace users will use to select their blocks.
- added ability to switch between the BlockFactory using tabs

Block Factory Tab:
screen shot 2016-07-22 at 8 06 26 pm

Block Export Tab (Have not yet implemented selector workspace):
screen shot 2016-07-22 at 8 06 13 pm

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/10)

### CODE REVIEW

**Comment by quachtina96** [comment]
@picklesrus @vicng  @evd2014 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10#-:-KNY2OPo00aSYWDmseqd:-133059691)_

**Comment by picklesrus** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blockfactory/factory.css, line 161 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYGXtaDjjqHH3nLWKB:-KNYGXtaDjjqHH3nLWKC:-1636831881) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.css#L161)):_

> ``` CSS
> #exportSettings {
>   margin: auto;
>   padding: 16px 16px;
> ```

Another css shortcut: If you want 16px padding all around, you can just say padding: 16px

---

_[demos/blockfactory/factory.css, line 173 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYGtYnKr7-enK4IOz_:-KNYGtYnKr7-enK4IOza:-931320270) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.css#L173)):_

> ``` CSS
> 
> .tab.tabon {
>   border-bottom-color: #ddd !important;
> ```

do you know why you need the important here?   I generally try and avoid it because it can make debugging css annoying.

---

_[demos/blockfactory/factory.js, line 871 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYjiZP4kIUkjcag7gu:-KNYjiZQrSmmw5mjKUxG:1081028026) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.js#L871)):_

> ``` JavaScript
>  * @param {string} elementID - ID of element to hide
>  */
> BlockFactory.hide = function(elementID) {
> ```

You may want to consider changing the display property directly (how you did below with visibility) rather than doing this.  By setting className = '' or className='hiding' you're wiping out any other class names you may have added to this element for styling. r

---

_[demos/blockfactory/index.html, line 39 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYwKGPjtSZ6h1BIHCD:-KNYwKGQJZtUtulCQLQ6:-1845944392) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/index.html#L39)):_

> ``` HTML
>     
>     <div id="exportSelector"></div>
>     
> ```

A note about html comments - I tend to leave them out so they don't get shipped to the client (more bytes = slowness).  Given the small amount of traffic on this page, it doesn't really matter, but just wanted to pass along.

---

_[demos/blockfactory/index.html, line 45 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYKeSx8hqRZ7UkN6FT:-KNYKeSx8hqRZ7UkN6FU:-1005689737) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/index.html#L45)):_

> ``` HTML
>       <form id="exportSettingsForm">
>         Download Block Definition:
>         <input type="checkbox" id="blockDefCheck"><br>
> ```

Just a note that you may end up wanting to use the built in closure components for little ui widgets (checkbox, dropdown, etc) since they provide some nice utilities and tend to work cross-browser, but this is fine as a placeholder.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 914 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNZ2tq-N19KYzs3C29v:-KNZ2tq-N19KYzs3C29w:557940560) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.js#L914)):_

> ``` JavaScript
>       blockFactoryTab.addEventListener('click',
>         function() {
>           blockFactoryTab.className = "tab tabon";
> ```

If it's possible to do with Closure, it'd be better if you could append/remove "tabon" and "taboff" instead of setting the explicit class name. This way if some other method modifies className, this method doesn't completely overwrite those changes.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 914 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNZ2tq-N19KYzs3C29v:-KNZ6XVOQxkcS2gPzrPW:-1007065467) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.js#L914)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> If it's possible to do with Closure, it'd be better if you could append/remove "tabon" and "taboff" instead of setting the explicit class name. This way if some other method modifies className, this method doesn't completely overwrite those changes.
> </details>
> This might help:
> http://clubmate.fi/javascript-adding-and-removing-class-names-from-elements/

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10)_

**Comment by quachtina96** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/factory.css, line 161 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYGXtaDjjqHH3nLWKB:-KNZ9_m6aEwfnUG7QNt-:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.css#L161)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> Another css shortcut: If you want 16px padding all around, you can just say padding: 16px
> </details>
> Done.

---

_[demos/blockfactory/factory.css, line 173 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYGtYnKr7-enK4IOz_:-KNZA1ipjif2b3EmR2ed:1740281830) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.css#L173)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> do you know why you need the important here?   I generally try and avoid it because it can make debugging css annoying.
> </details>
> Removed!

---

_[demos/blockfactory/factory.js, line 871 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNYjiZP4kIUkjcag7gu:-KNZA4cPsj8j4tsPFZjl:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.js#L871)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> You may want to consider changing the display property directly (how you did below with visibility) rather than doing this.  By setting className = '' or className='hiding' you're wiping out any other class names you may have added to this element for styling. r
> </details>
> Done.

---

_[demos/blockfactory/factory.js, line 914 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNZ2tq-N19KYzs3C29v:-KNZA59y9l5fomWCAvZD:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.js#L914)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> This might help:
> http://clubmate.fi/javascript-adding-and-removing-class-names-from-elements/
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 914 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNZ2tq-N19KYzs3C29v:-KNZKLJXBq_v6UkcUfpB:1468727089) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.js#L914)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> Done.
> </details>
> What happens if `tabon` or `taboff` hasn't been defined yet?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10)_

**Comment by quachtina96** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 914 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/10#-KNZ2tq-N19KYzs3C29v:-KNZYhhfPTFax3Spf_zo:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/7e3d311f0b30a397aac27d0268793608807812b7/demos/blockfactory/factory.js#L914)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> What happens if `tabon` or `taboff` hasn't been defined yet?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10)_

**Comment by vicng** [comment]
After Katelyn's comments, :lgtm: 

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/10#-:-KNZZMNGvSJFJsyLoS7L:-644452951)_

**Pull request merged**
