### PR TITLE
Block Exporter #3: Disable/Enable Blocks when Selected

### PR DESCRIPTION
**Pull request by quachtina96**
In the selector workspace, the user is limited to one block of a given type, ensuring that they don't have multiple copies of the same block definition or generator stub.
- When a block is created on the workspace, disable the block in the selector toolbox.
- When a block is deleted from the workspace, enable the block in the selector toolbox.

Also updates the helper text accordingly by showing what blocks are currently selected.

screen shot 2016-08-01 at 4 14 34 pm

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/14)

### CODE REVIEW

**Comment by quachtina96** [comment]
@picklesrus @vicng @evd2014 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/14#-:-KO7PEH6GjtMwOdXYrnj:-169138557)_

**Comment by vicng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/block_exporter_controller.js, line 117 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7dR_N4odt0per1Q9F:-KO7dR_Ooq5Eqqus3D7m:11863962) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L117)):_

> ``` JavaScript
>  * @param {string} blockType - type of block to disable
>  */
> BlockExporterController.prototype.disableBlock = function(blockType) {
> ```

disableBlock and enableBlock are very similar in terms of code. It seems better if you could merge them into one like:

setBlockEnabled(blockType, enabled)

(The wording here is awkward, but you get the idea)

---

_[demos/blockfactory/block_exporter_controller.js, line 159 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7a2fDKyDbKScbBkav:-KO7a2fDKyDbKScbBkaw:871260393) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L159)):_

> ``` JavaScript
>  * @param {!Blockly.Events} event - The fired Blockly event.
>  */
> BlockExporterController.prototype.onSelectBlockForExport = function(event) {
> ```

If possible, mark as private.

---

_[demos/blockfactory/block_exporter_controller.js, line 181 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7aDbk-dOOHmYX0N2P:-KO7aDbk-dOOHmYX0N2Q:-292362759) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L181)):_

> ``` JavaScript
>  * @param {!Blockly.Events} event - The fired Blockly event.
>  */
> BlockExporterController.prototype.onDeselectBlockForExport = function(event) {
> ```

Mark private.

---

_[demos/blockfactory/block_exporter_controller.js, line 190 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7czipFZmR27QuzJhQ:-KO7czipFZmR27QuzJhR:177118030) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L190)):_

> ``` JavaScript
>     this.enableBlock(blockType);
>     // Edit helper text (currently selected)
>     var selectedBlocksText = this.getSelectedBlockTypes_().join(', ');
> ```

These two lines should be in the View class.

---

_[demos/blockfactory/block_exporter_controller.js, line 198 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7aFZt974Pd-haUFLk:-KO7aFZt974Pd-haUFLl:231692608) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L198)):_

> ``` JavaScript
>  * Add change listeners to the exporter's selector workspace.
>  */
> BlockExporterController.prototype.addChangeListenersToSelectorWorkspace
> ```

In general, I try to organize method declarations in the way people will tend to read it (from top-down).

A couple of ordering rules I use are (these aren't set in stone -- use your best judgment):
- public before private
- method dependencies are declared after those that use them.

In this case, I'd move it so the ordering is:

addChangeListenersToSelectorWorkspace
onSelectBlockForExport
onDeselectBlockForExport

---

_[demos/blockfactory/block_exporter_controller.js, line 199 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7_TWXxWYl-xN7qG3q:-KO7_TWXxWYl-xN7qG3r:261697827) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L199)):_

> ``` JavaScript
>  */
> BlockExporterController.prototype.addChangeListenersToSelectorWorkspace
>     = function() {
> ```

Fix indentation? (I think it's off, but not sure what the rules are for JS tbh.)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/14)_

**Comment by quachtina96** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/block_exporter_controller.js, line 117 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7dR_N4odt0per1Q9F:-KO7md10en35R09ey9He:-2038726383) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L117)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> disableBlock and enableBlock are very similar in terms of code. It seems better if you could merge them into one like:
> 
> setBlockEnabled(blockType, enabled)
> 
> (The wording here is awkward, but you get the idea)
> 
> </details>
> Done. setBlockDisabled is the new function.

---

_[demos/blockfactory/block_exporter_controller.js, line 159 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7a2fDKyDbKScbBkav:-KO7mrujnevofpy1VPRA:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L159)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> If possible, mark as private.
> </details>
> Done.

---

_[demos/blockfactory/block_exporter_controller.js, line 181 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7aDbk-dOOHmYX0N2P:-KO7n56sxb0BjSHUSQPv:-469593350) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L181)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Mark private.
> </details>
> done!

---

_[demos/blockfactory/block_exporter_controller.js, line 190 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7czipFZmR27QuzJhQ:-KO7n6QWT5kiU4tqMHe0:677588487) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L190)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> These two lines should be in the View class.
> </details>
> done

---

_[demos/blockfactory/block_exporter_controller.js, line 198 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7aFZt974Pd-haUFLk:-KO7n8ViIVCi1k_zTzMv:-1215270890) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L198)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> In general, I try to organize method declarations in the way people will tend to read it (from top-down).
> 
> A couple of ordering rules I use are (these aren't set in stone -- use your best judgment):
> - public before private
> - method dependencies are declared after those that use them.
> 
> In this case, I'd move it so the ordering is:
> 
> addChangeListenersToSelectorWorkspace
> onSelectBlockForExport
> onDeselectBlockForExport
> 
> </details>
> done and will keep in mind for the future!

---

_[demos/blockfactory/block_exporter_controller.js, line 199 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7_TWXxWYl-xN7qG3q:-KO7n75EQZeT66JL6SLz:677588487) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L199)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Fix indentation? (I think it's off, but not sure what the rules are for JS tbh.)
> </details>
> done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/14)_

**Comment by vicng** [comment]
:lgtm: after change

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/block_exporter_controller.js, line 117 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7dR_N4odt0per1Q9F:-KO7zOl0ImHGoIR3dW3E:-954336234) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L117)):_
<details><summary>

<i>Previously, quachtina96 wrote…</i></summary>



> Done. setBlockDisabled is the new function.
> </details>
> Use the positive version for the method name (ie. setBlockEnabled). It's hard to read double negatives (eg. `setBlockDisabled(block, false)`)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/14#-:-KO8-AtkVzdsVCXPVgYq:939295587)_

**Comment by quachtina96** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/block_exporter_controller.js, line 117 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/14#-KO7dR_N4odt0per1Q9F:-KO850VL48QMTUtuKtip:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/263b22bcfeac4d064cc7044441ee6e61b7323668/demos/blockfactory/block_exporter_controller.js#L117)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Use the positive version for the method name (ie. setBlockEnabled). It's hard to read double negatives (eg. `setBlockDisabled(block, false)`)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/14)_

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/14#-:-KOBsOFrKbZTOMaoGnkf:1417088721)_

**Pull request merged**
