### PR TITLE
Block Exporter: 'Select All Blocks' button for export

### PR DESCRIPTION
**Pull request by quachtina96**
User can select all blocks in block library for export and deselect blocks from there. This saves users time because they won't need to select every block by hand.

screen shot 2016-08-04 at 11 17 22 am
### app_controller.js
- added 'Select All Blocks' Button click handler
### block_exporter_controller.js
- added selectAllBlocks function
### block_exporter_tools.js
- made addBlockDefinitions public so I could use it in block exporter controller.
### block_exporter_view.js
- added functions to add blocks to selector workspace and to clean up the workspace
### index.html
- added spacing and 'Select All Blocks' button

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/23)

### CODE REVIEW

**Comment by quachtina96** [comment]
@picklesrus @evd2014 @vicng 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/23#-:-KOLn-REsb7eMstdytPu:-644199623)_

**Comment by edauterman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[demos/blockfactory/block_exporter_controller.js, line 224 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KOMVrqcaCgMSWgvslUg:-KOMVrqcaCgMSWgvslUh:2123010844) ([raw file](https://github.com/quachtina96/blockly/blob/9f2e1fdbb30814d04644a7797b1b1f12d4ec8188/demos/blockfactory/block_exporter_controller.js#L224)):_

> ``` JavaScript
> 
>   // For every block, render in selector workspace.
>   for (var i = 0; i < allBlockTypes.length; i++) {
> ```

I've found the following syntax really useful for iterating over a list of blocks (no pressure to use it, functionally the same):
for (var i = 0, block; block = allBlockTypes[i]; i++) {
    this.view.selectBlock(block)
}

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/23)_

**Comment by quachtina96** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[demos/blockfactory/block_exporter_controller.js, line 224 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KOMVrqcaCgMSWgvslUg:-KOMZXl3rqppABnklLA0:-1604557953) ([raw file](https://github.com/quachtina96/blockly/blob/9f2e1fdbb30814d04644a7797b1b1f12d4ec8188/demos/blockfactory/block_exporter_controller.js#L224)):_
<details><summary>

<i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>



> I've found the following syntax really useful for iterating over a list of blocks (no pressure to use it, functionally the same):
> for (var i = 0, block; block = allBlockTypes[i]; i++) {
>     this.view.selectBlock(block)
> }
> </details>
> Thanks! I've changed my for loops to use that syntax for this file.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/23)_

**Comment by edauterman** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/23#-:-KOM_MbHErURy8Rtp1D3:1417088721)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/block_exporter_controller.js, line 43 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KOMzZziedyiyKaQuhCR:-KOMzZziedyiyKaQuhCS:-1841723652) ([raw file](https://github.com/quachtina96/blockly/blob/791249104eb886e875b2aaaa21c43d96788e272c/demos/blockfactory/block_exporter_controller.js#L43)):_

> ``` JavaScript
>   var selectedBlocks = this.view.getSelectedBlocks();
>   var blockTypes = [];
>   for (var i = 0, block; block = selectedBlocks[i]; i++) {
> ```

Does this work? The middle clause is an assignment, not a comparison. I would think it'd eventually cause an index out of bounds error -- or does out of bounds index just return `nil` or `undefined`?

Why was this changed? Is this a JS convention?

---

_[demos/blockfactory/block_exporter_controller.js, line 114 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KOMzMKuKCtDbd61Qd0H:-KOMzMKuKCtDbd61Qd0I:160841994) ([raw file](https://github.com/quachtina96/blockly/blob/791249104eb886e875b2aaaa21c43d96788e272c/demos/blockfactory/block_exporter_controller.js#L114)):_

> ``` JavaScript
>   // Disable any selected blocks.
>   var selectedBlocks = this.getSelectedBlockTypes_();
>   for (var i = 0, blockType; blockType = selectedBlocks[i]; i++) {
> ```

Same as above.

---

_[demos/blockfactory/block_exporter_controller.js, line 214 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KON-lEi62_RLIbE63E9:-KON-lEi62_RLIbE63EA:-1687495831) ([raw file](https://github.com/quachtina96/blockly/blob/791249104eb886e875b2aaaa21c43d96788e272c/demos/blockfactory/block_exporter_controller.js#L214)):_

> ``` JavaScript
>  * Selects all blocks on the selector workspace.
>  */
> BlockExporterController.prototype.selectAllBlocks = function() {
> ```

addAllBlocksToWorkspace is a better name for the function.

selectAllBlocks is misleading

---

_[demos/blockfactory/block_exporter_controller.js, line 224 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KON-LqWaG-Vy6ptO8Id:-KON-LqWaG-Vy6ptO8Ie:-1715826953) ([raw file](https://github.com/quachtina96/blockly/blob/791249104eb886e875b2aaaa21c43d96788e272c/demos/blockfactory/block_exporter_controller.js#L224)):_

> ``` JavaScript
> 
>   // For every block, render in selector workspace.
>   for (var i = 0, blockType; blockType = allBlockTypes[i]; i++) {
> ```

Same thing here.

---

_[demos/blockfactory/index.html, line 78 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KON0FqZtt3k6CZBcF6x:-KON0FqZtt3k6CZBcF6y:735832282) ([raw file](https://github.com/quachtina96/blockly/blob/791249104eb886e875b2aaaa21c43d96788e272c/demos/blockfactory/index.html#L78)):_

> ``` HTML
>         <br>
>         <br>
>         <button id="clearSelectedButton"> Clear Selected Blocks </button>
> ```

These buttons make more sense above the workspace (probably above the helper text)

---

_[demos/blockfactory/index.html, line 79 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/23#-KON05I8pSgdO-EdLdOw:-KON05I8pSgdO-EdLdOx:-1830061573) ([raw file](https://github.com/quachtina96/blockly/blob/791249104eb886e875b2aaaa21c43d96788e272c/demos/blockfactory/index.html#L79)):_

> ``` HTML
>         <br>
>         <button id="clearSelectedButton"> Clear Selected Blocks </button>
>         <button id="selectAllButton">Select All Blocks </button>
> ```

Rename to "Add All Blocks from Storage"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/23)_

**Comment by quachtina96** [comment]
I have a version of blockFactoryExpansion that has been based off the most recent master and I rebased my selectAllBlocks branch off of that new version. As a result, the diff in my most recent push introduce over a hundred changes. To make reviewing more easy, I'm creating a new pull request in which the diff is solely related to the changes I made.

**Pull request closed without merging**
