### PR TITLE
Cleaned up Block Library API

### PR DESCRIPTION
**Pull request by quachtina96**
- fixed bug in addOption() to update currently selected block (in dropdown) upon saving block to library.
- added getSelected function to BlockLibrary UI (used in Controller's select handler)
- created an openBlock function that updates the BlockFactory in the select handler
- fixed typo, changing UNNAMED to BlockFactory.UNNAMED

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/9)

### CODE REVIEW

**Comment by quachtina96** [comment]
@picklesrus @vicng @evd2014 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/9#-:-KNK7771pc2dBX3WUi1R:-169138557)_

**Comment by vicng** [comment]
Small changes

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[demos/blockfactory/block_library_controller.js, line 62 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/9#-KNKLHHESQM_6aaS0mcO:-KNKLHHFp7olSutIbXuN:-702501228) ([raw file](https://github.com/quachtina96/blockly/blob/7547d6ed44982ad6b15ae41c085d96c1e4d36477/demos/blockfactory/block_library_controller.js#L62)):_

> ``` JavaScript
>  * @param {Element} blockLibraryDropdown - your block library dropdown
>  */
> BlockLibrary.Controller.selectHandler = function(blockLibraryDropdown) {
> ```

You might want to change `selectHandler` to something more descriptive like "onSelectedBlockChanged".

---

_[demos/blockfactory/block_library_UI.js, line 10 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/9#-KNKM43VSIYjBPRuZGJm:-KNKM43VSIYjBPRuZGJn:1215220083) ([raw file](https://github.com/quachtina96/blockly/blob/7547d6ed44982ad6b15ae41c085d96c1e4d36477/demos/blockfactory/block_library_UI.js#L10)):_

> ``` JavaScript
> 'use strict';
> 
> goog.provide('BlockLibrary.UI');
> ```

Can you change the filename to be all lowercase? (Same with any other files, if necessary)

---

_[demos/blockfactory/block_library_UI.js, line 25 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/9#-KNKLzb_PHDae627boPI:-KNKLzb_PHDae627boPJ:-1167008838) ([raw file](https://github.com/quachtina96/blockly/blob/7547d6ed44982ad6b15ae41c085d96c1e4d36477/demos/blockfactory/block_library_UI.js#L25)):_

> ``` JavaScript
>   option.text = optionText;
>   option.value = optionName;
>   option.selected = true;
> ```

Maybe add selected as a parameter?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/9#-:-KNKMF5i0R9eT5ppUuI_:1689307045)_

**Comment by quachtina96** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

_[demos/blockfactory/block_library_controller.js, line 62 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/9#-KNKLHHESQM_6aaS0mcO:-KNKMmVY_4Y4mqv-ToLb:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/7547d6ed44982ad6b15ae41c085d96c1e4d36477/demos/blockfactory/block_library_controller.js#L62)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> You might want to change `selectHandler` to something more descriptive like "onSelectedBlockChanged".
> </details>
> Done.

---

_[demos/blockfactory/block_library_UI.js, line 10 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/9#-KNKM43VSIYjBPRuZGJm:-KNKMz2oS7Jfg1uT4koc:-1519881840) ([raw file](https://github.com/quachtina96/blockly/blob/7547d6ed44982ad6b15ae41c085d96c1e4d36477/demos/blockfactory/block_library_UI.js#L10)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Can you change the filename to be all lowercase? (Same with any other files, if necessary)
> </details>
> Done, but not shown in reviewable for some reason

---

_[demos/blockfactory/block_library_UI.js, line 25 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/9#-KNKLzb_PHDae627boPI:-KNKNAmZ2iqViL1m8gSp:-469593350) ([raw file](https://github.com/quachtina96/blockly/blob/7547d6ed44982ad6b15ae41c085d96c1e4d36477/demos/blockfactory/block_library_UI.js#L25)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Maybe add selected as a parameter?
> </details>
> done!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/9)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

_[demos/blockfactory/block_library_UI.js, line 10 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/9#-KNKM43VSIYjBPRuZGJm:-KNKUWQCuCzb9V-3VbHC:-1530778263) ([raw file](https://github.com/quachtina96/blockly/blob/7547d6ed44982ad6b15ae41c085d96c1e4d36477/demos/blockfactory/block_library_UI.js#L10)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> Done, but not shown in reviewable for some reason
> </details>
> Yeah, there's some oddity with changing filenames. The change might go through, but if it doesn't we can fix later if need be.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/9#-:-KNKV0zp85-1088nLWfc:1417088721)_

**Pull request merged**
