### PR TITLE
Refactor Block Library Code into Separate Files

### PR DESCRIPTION
**Pull request by quachtina96**
factory.js - provides BlockFactory namespace, provides Block Factory functions
blockLibrary.js - provides namespace for Block Library
blockLibraryUI.js - API for controlling Block Library Dropdown
blockLibraryStorage.js - Storage class; API for storing blocks in local storage
blockLibraryController.js - depends on Block Library UI & Storage
blockLibraryExporter.js - Exporter Class; API for exporting starter code for programming blocks
init.js - holds in the init function for Block Factory

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/8)

### CODE REVIEW

**Comment by quachtina96** [comment]
@picklesrus @vicng @evd2014 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/8#-:-KNJpNSNRV5wXbf5XTfo:666604291)_

**Comment by vicng** [comment]
Small nits, but :lgtm: 

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

_[demos/blockfactory/factory.css, line 38 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNJyTfhDeHVnrC7WE-U:-KNJyTfhDeHVnrC7WE-V:1149162186) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/factory.css#L38)):_

> ``` CSS
>   -webkit-margin-start: 0px;
>   -webkit-margin-end: 0px;
>   padding-top: 16px;
> ```

Use the shortform padding.

---

_[demos/blockfactory/factory.js, line 30 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNJyZ7AQsSeL0_PUaf9:-KNJyZ7AQsSeL0_PUafA:-1425686616) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/factory.js#L30)):_

> ``` JavaScript
>  */
> goog.provide('BlockFactory');
> ```

Nit: Remove extra line.

---

_[demos/blockfactory/index.html, line 13 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNK0dJ1hCdp5wntC09J:-KNK0dJ2ki_K76kLRJhR:1985537568) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/index.html#L13)):_

> ``` HTML
>   <script src="../../generators/javascript.js"></script>
>   <script src="factory.js"></script>
>   <script src="blockLibrary.js"></script>
> ```

Rename these as block_library_*

---

_[demos/blockfactory/index.html, line 76 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNK0pADdyV_s3wIVuu-:-KNK0pADdyV_s3wIVuu0:1740807594) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/index.html#L76)):_

> ``` HTML
>                 <span class=>Import block</span>
>               </label>
>               <input id="files"  type="file" name="files"
> ```

Nit extra space

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/8#-:-KNK0vEytXkZJv1f8byQ:290636457)_

**Comment by quachtina96** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

_[demos/blockfactory/factory.css, line 38 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNJyTfhDeHVnrC7WE-U:-KNK1e8EXGE6wk_ZUIit:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/factory.css#L38)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Use the shortform padding.
> </details>
> Done.

---

_[demos/blockfactory/factory.js, line 30 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNJyZ7AQsSeL0_PUaf9:-KNK28Ny_XVcBjO9YZmN:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/factory.js#L30)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Remove extra line.
> </details>
> Done.

---

_[demos/blockfactory/index.html, line 13 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNK0dJ1hCdp5wntC09J:-KNK27e_fjET9wQlgDMD:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/index.html#L13)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Rename these as block_library_*
> </details>
> Done.

---

_[demos/blockfactory/index.html, line 76 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/8#-KNK0pADdyV_s3wIVuu-:-KNK2MW8oae_L4uZfMJv:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/1cf623557e485ad3c0d1791d604aa9656670868d/demos/blockfactory/index.html#L76)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit extra space
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/8)_

**Comment by picklesrus** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/8#-:-KNK3PF3PWhz36m5_-jv:1417088721)_

**Pull request merged**
