### PR TITLE
Block Factory Expansion: Refactor

### PR DESCRIPTION
**Pull request by quachtina96**
# Refactor
## block_factory_expansion.js
- Block Factory Expansion is a Class--not a namespace
- Its Block Factory Expansion’s init function is split up into multiple functions 
## factory.js
- Reorganized Block Factory functions
- Added comments to section and label related functions
## block_library_controller.js
-  moved event handler for block selection out to block_factory_expansion
-  created a function that returns the selected block type and is called in block_factory_expasion to update the block factory.
# Misc. Changes
- Disable save to block library button when on manual mode.

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/15)

### CODE REVIEW

**Comment by quachtina96** [comment]
@evd2014 @picklesrus @vicng This one is harder to read through but the changes are quite simple as described in pull request description. 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15#-:-KOBp4Q10CGOwqKwLcZ7:-2132361266)_

**Comment by picklesrus** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[demos/blockfactory/block_factory_expansion.js, line 37 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOBwAa61fAceGHucv7K:-KOBwAa7sn4Ma4ZQK-og:8086994) ([raw file](https://github.com/quachtina96/blockly/blob/af1a5a0706078f378e8de1038c76f2d0a7cb591c/demos/blockfactory/block_factory_expansion.js#L37)):_

> ``` JavaScript
>     = function(blockLibraryDropdown) {
>   var self = this;
>   var onSelect = function(blockLibraryDropdown) {
> ```

I'm a little confused by this part.  You're not calling this onselect function anywhere else, are you?
So couldn't this just be the innards of the onselect function i.e. the following:

var blockType = this.blocklyLibraryController.getSelectedBlockType(dropdown);
this.blockLibraryController.openBlock(blockType);

---

_[demos/blockfactory/block_factory_expansion.js, line 58 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOC1OGDQT0BW0X1M4IS:-KOC1OGDQT0BW0X1M4IT:-1073438218) ([raw file](https://github.com/quachtina96/blockly/blob/af1a5a0706078f378e8de1038c76f2d0a7cb591c/demos/blockfactory/block_factory_expansion.js#L58)):_

> ``` JavaScript
>       // keep the reference to this object upon tab click.
>       var self = this;
>       var addTabHandler = function(blockFactoryTabID, blockExporterTabID){
> ```

similar question here about the addTableHandler function as onselect

---

_[demos/blockfactory/factory.js, line 50 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOBxlsRidhJJ5JcnxHd:-KOBxlsRidhJJ5JcnxHe:-407409365) ([raw file](https://github.com/quachtina96/blockly/blob/af1a5a0706078f378e8de1038c76f2d0a7cb591c/demos/blockfactory/factory.js#L50)):_

> ``` JavaScript
> 
> /**
>  * Existing direction ('ltr' vs 'rtl') of preview.
> ```

This is all just re-arranged right? There isn't any new or changed functionality?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15)_

**Comment by quachtina96** [comment]
I rebased my pull request on the most recent version of my master (blockFactoryExpansion) and that's why the commit list is so long.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

_[demos/blockfactory/block_factory_expansion.js, line 37 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOBwAa61fAceGHucv7K:-KOCSRuskBlRESWNP3b9:324494799) ([raw file](https://github.com/quachtina96/blockly/blob/af1a5a0706078f378e8de1038c76f2d0a7cb591c/demos/blockfactory/block_factory_expansion.js#L37)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> I'm a little confused by this part.  You're not calling this onselect function anywhere else, are you?
> So couldn't this just be the innards of the onselect function i.e. the following:
> 
> var blockType = this.blocklyLibraryController.getSelectedBlockType(dropdown);
> this.blockLibraryController.openBlock(blockType);
> 
> </details>
> done! removed unneeded closure

---

_[demos/blockfactory/block_factory_expansion.js, line 58 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOC1OGDQT0BW0X1M4IS:-KOCVPuk9r8cPMmdSP2H:576686609) ([raw file](https://github.com/quachtina96/blockly/blob/af1a5a0706078f378e8de1038c76f2d0a7cb591c/demos/blockfactory/block_factory_expansion.js#L58)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> similar question here about the addTableHandler function as onselect
> </details>
> It's needed to maintain the click handlers for the tabs.

---

_[demos/blockfactory/factory.js, line 50 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOBxlsRidhJJ5JcnxHd:-KOCJrNcgD1_ohA3TbKm:895810233) ([raw file](https://github.com/quachtina96/blockly/blob/af1a5a0706078f378e8de1038c76f2d0a7cb591c/demos/blockfactory/factory.js#L50)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> This is all just re-arranged right? There isn't any new or changed functionality?
> </details>
> Yeah, I only rearranged and added some clarifying comments.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15#-:-KOCW2nBhfMmMRANXsHy:888885080)_

**Comment by edauterman** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blockfactory/block_factory_expansion.js, line 94 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOCaPi4QPc2DAEmVtDP:-KOCaPi5x2fGsxQfYCU-:-910749181) ([raw file](https://github.com/quachtina96/blockly/blob/5930066a22cbd92c776c43065272a8aa497f9b74/demos/blockfactory/block_factory_expansion.js#L94)):_

> ``` JavaScript
>  */
> BlockFactoryExpansion.prototype.onExporterTab =
>     function(blockFactoryTab, blockExporterTab, bfeSelf) {
> ```

Looks like you don't need this since you can get self from this. Just use var bfeSelf = this. 

Also make sure to comment your parameters.

---

_[demos/blockfactory/block_library_controller.js, line 75 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOCbAZ-920CfaYFxDuy:-KOCbAZ0yJtKrgwN6yES:-595026260) ([raw file](https://github.com/quachtina96/blockly/blob/5930066a22cbd92c776c43065272a8aa497f9b74/demos/blockfactory/block_library_controller.js#L75)):_

> ``` JavaScript
>  *
>  * @param {Element} blockLibraryDropdown - The block library dropdown.
>  */
> ```

Add @return

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15)_

**Comment by quachtina96** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blockfactory/block_factory_expansion.js, line 58 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOC1OGDQT0BW0X1M4IS:-KOCkb-5Rw7uh1eMfpVv:-797765235) ([raw file](https://github.com/quachtina96/blockly/blob/af1a5a0706078f378e8de1038c76f2d0a7cb591c/demos/blockfactory/block_factory_expansion.js#L58)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> It's needed to maintain the click handlers for the tabs.
> </details>
> removed the extra function  in revision 3

---

_[demos/blockfactory/block_factory_expansion.js, line 94 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOCaPi4QPc2DAEmVtDP:-KOCh7yXQuGytZs79V7a:-418517908) ([raw file](https://github.com/quachtina96/blockly/blob/5930066a22cbd92c776c43065272a8aa497f9b74/demos/blockfactory/block_factory_expansion.js#L94)):_
<details><summary>

<i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>



> Looks like you don't need this since you can get self from this. Just use var bfeSelf = this. 
> 
> Also make sure to comment your parameters.
> </details>
> Done & simplified code.

---

_[demos/blockfactory/block_library_controller.js, line 75 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KOCbAZ-920CfaYFxDuy:-KOCiTMnEYM0d84H4e27:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/5930066a22cbd92c776c43065272a8aa497f9b74/demos/blockfactory/block_library_controller.js#L75)):_
<details><summary>

<i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>



> Add @return
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15)_

**Comment by vicng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/block_factory_expansion.js, line 15 [r3]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KODAuyW-e6-u6I-xvzl:-KODAuyW-e6-u6I-xvzm:785851938) ([raw file](https://github.com/quachtina96/blockly/blob/3a1b7f126caafbd844734eff2eea57b47a38e9b1/demos/blockfactory/block_factory_expansion.js#L15)):_

> ``` JavaScript
> goog.require('goog.dom.classlist');
> 
> BlockFactoryExpansion = function() {
> ```

Name could be better. Maybe rename to "AppController" or something? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15)_

**Comment by quachtina96** [comment]
once again, I rebased. 

---

Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

_[demos/blockfactory/app_controller.js, line 15 [r3]](https://reviewable.io:443/reviews/quachtina96/blockly/15#-KODAuyW-e6-u6I-xvzl:-KOGgiFxL3CXJLid4f9G:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/3a1b7f126caafbd844734eff2eea57b47a38e9b1/demos/blockfactory/app_controller.js#L15)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Name could be better. Maybe rename to "AppController" or something? 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15#-:-KOGglEe1d-6toYfl1Yv:785350657)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15#-:-KOHj4vf7kC1lkJZ1vqj:1417088721)_

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15#-:-KOHlLwyshZRw3WB1vop:1417088721)_

**Comment by edauterman** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/15#-:-KOHlrj0kC_Do_8EYMxL:1417088721)_

**Pull request merged**
