### PR TITLE
Block Library Export

### PR DESCRIPTION
**Pull request by quachtina96**
**In factory.js**
Created Block Library Export Namespace, which contains getBlockDefs function and the getGeneratorCode function. 
- getBlockDefs returns the language code for multiple blocks, given the list of block types of interest and the desired format.
- getGeneratorCode returns the generator stubs for multiple blocks, given the list of block types of interest and the desired language.

In order to build upon Block Factory's infrastructure, Block Factory Export has its own preview and main workspaces that are used in getBlockDefs and in getGeneratorCode.

**in index.html**
- houses the hidden divs that hold the export workspaces.

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/7)

### CODE REVIEW

**Comment by quachtina96** [comment]
@vicng @picklesrus @evd2014 

Let me know if in a separate CL, I should turn the Export into a class rather than have it as a namespace. I also know i have a TODO in there in regards to injecting the export workspaces--considering having that within the constructor of the Export class, where parameters would be the id's of the div in which we inject the workspace.

Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7#-:-KN4XcNOJZD2x_ZIZisR:-941833519)_

**Comment by picklesrus** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 912 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8sw7SaikNvlN9GzZx:-KN8sw7SaikNvlN9GzZy:-497491235) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L912)):_

> ``` JavaScript
>  * Saves block to block library.
>  *
>  * @param {string} blockType - name of block
> ```

If this is really the name of the block, not the type, the variable name should probably be changed to blockName. Same for removeBlock below.

---

_[demos/blockfactory/factory.js, line 1066 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8tdrKoKtOroC4t8ne:-KN8tdrLxAv9wO3ZP_yh:-1890378742) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1066)):_

> ``` JavaScript
>  * @type {Blockly.Workspace}
>  */
> BlockLibrary.Export.mainWorkspace = null;
> ```

I wonder if a different variable name would be useful.  You already have a mainWorkspace above (different namespace I know),  but I still got confused for a moment.

Maybe:
blockBuilderWorkspace
previewWorkspace
exporterWorkspace?

Except, I forget what your demo looks like so am having a hard time remembering what the exporter workspace is for.  Would you show me again? 

---

_[demos/blockfactory/factory.js, line 1145 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8zTftrDi7QqO3XO0r:-KN8zTfu6wimX-oq948-:-1551773699) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1145)):_

> ``` JavaScript
>  * @return {string} generator code for multiple blocks.
>  */
> BlockLibrary.Export.updateGenerator = function(block, generatorLanguage){
> ```

This is pretty close to the code in the updateGenerator function above.  Is there a reason not to use that one?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7)_

**Comment by vicng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 1066 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN99AXWRP4qAlhlH_8p:-KN99AXWRP4qAlhlH_8q:1023929493) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1066)):_

> ``` JavaScript
>  * @type {Blockly.Workspace}
>  */
> BlockLibrary.Export.mainWorkspace = null;
> ```

You're right in that Export should be a class and not a namespace.

Objects first, static methods second, global variables almost never! :)

---

_[demos/blockfactory/factory.js, line 1083 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN9C-5TOoSnzVOZJ_Yb:-KN9C-5TOoSnzVOZJ_Yc:-1197735971) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1083)):_

> ``` JavaScript
>  * language code.
>  */
> BlockLibrary.Export.getBlockDefs = function(blockTypes, definitionFormat) {
> ```

Are the 2 methods below supposed to replace something from above? The code that is being replaced should be deleted within this CL too. It makes it easier for us to see what is refactored code and what is new code.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7)_

**Comment by quachtina96** [comment]
_[demos/blockfactory/factory.js, line 1145 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8zTftrDi7QqO3XO0r:-KN9c2Tf-THklgoHnKGM:1591102602) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1145)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> This is pretty close to the code in the updateGenerator function above.  Is there a reason not to use that one?
> </details>
> the updateGenerator code  injects the code into the generator preview text area whereas I just want it 
> called at the end of it, but I can move it out so that I can reuse the updateGenerator function.

does that sound good?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7)_

**Comment by quachtina96** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 912 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8sw7SaikNvlN9GzZx:-KN9b4xA7zwOnczRojn0:1824497639) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L912)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> If this is really the name of the block, not the type, the variable name should probably be changed to blockName. Same for removeBlock below.
> </details>
> changed from name of block to type of block. block name and block type are synonymous, but in the code i've been using block type since we are literally looking at the block's type. 

---

_[demos/blockfactory/factory.js, line 1066 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8tdrKoKtOroC4t8ne:-KN9bPGtoRb7bRYoelqC:583417966) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1066)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> I wonder if a different variable name would be useful.  You already have a mainWorkspace above (different namespace I know),  but I still got confused for a moment.
> 
> Maybe:
> blockBuilderWorkspace
> previewWorkspace
> exporterWorkspace?
> 
> Except, I forget what your demo looks like so am having a hard time remembering what the exporter workspace is for.  Would you show me again? 
> 
> </details>
> yes, the exporter has its own main and own preview workspaces so that the xml stored in the block library can go through the same pipeline to generate the block definitions and generator stubs for the blocks selected for export.

I call it Export.mainWorkspace because it is a parallel that of the blockfactory main workspace.

---

_[demos/blockfactory/factory.js, line 1083 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN9C-5TOoSnzVOZJ_Yb:-KN9bvHQCZyF6NfuhPks:1515870533) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1083)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Are the 2 methods below supposed to replace something from above? The code that is being replaced should be deleted within this CL too. It makes it easier for us to see what is refactored code and what is new code.
> </details>
> No, they aren't supposed to replace code from above.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7)_

**Comment by quachtina96** [comment]
_[demos/blockfactory/factory.js, line 1066 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN99AXWRP4qAlhlH_8p:-KN9loUEg-0csOhisjKZ:-469593257) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1066)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> You're right in that Export should be a class and not a namespace.
> 
> Objects first, static methods second, global variables almost never! :)
> </details>
> done~

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7)_

**Comment by vicng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 1066 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN99AXWRP4qAlhlH_8p:-KNEQS0dT2fZY2rDOkCO:-1186513115) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1066)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> done~
> </details>
> Is it possible to create a workspace without a hidden div or by creating a hidden div inside the exporter and using that? It'd be ideal if the Controller could just create an Exporter and not have to worry about specifying a hidden div.

---

_[demos/blockfactory/factory.js, line 1083 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN9C-5TOoSnzVOZJ_Yb:-KNE1Xv27HEzP0oeR_n7:-551321671) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1083)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> No, they aren't supposed to replace code from above.
> </details>
> Will the above code eventually get deleted? This method is very similar to updateLanguage(), so I assume that will go away eventually.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7)_

**Comment by quachtina96** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blockfactory/factory.js, line 912 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8sw7SaikNvlN9GzZx:-KNJWpwJE498YpKWWhPQ:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L912)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> changed from name of block to type of block. block name and block type are synonymous, but in the code i've been using block type since we are literally looking at the block's type. 
> </details>
> Done.

---

_[demos/blockfactory/factory.js, line 1066 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN99AXWRP4qAlhlH_8p:-KNEaADs4LdjXfhX_Bf9:-609628044) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1066)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Is it possible to create a workspace without a hidden div or by creating a hidden div inside the exporter and using that? It'd be ideal if the Controller could just create an Exporter and not have to worry about specifying a hidden div.
> </details>
> done in next CL

---

_[demos/blockfactory/factory.js, line 1066 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8tdrKoKtOroC4t8ne:-KNJWrnzhJ9BGPILGvRP:-499146009) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1066)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> yes, the exporter has its own main and own preview workspaces so that the xml stored in the block library can go through the same pipeline to generate the block definitions and generator stubs for the blocks selected for export.
> 
> I call it Export.mainWorkspace because it is a parallel that of the blockfactory main workspace.
> </details>
> Done.

---

_[demos/blockfactory/factory.js, line 1083 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN9C-5TOoSnzVOZJ_Yb:-KNJWMoMX7gv7Wkf7Ri3:85034790) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1083)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Will the above code eventually get deleted? This method is very similar to updateLanguage(), so I assume that will go away eventually.
> </details>
> created getBlockDef function from update

---

_[demos/blockfactory/factory.js, line 1145 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/7#-KN8zTftrDi7QqO3XO0r:-KNJRaICZUh_ZSCdaq2N:871182422) ([raw file](https://github.com/quachtina96/blockly/blob/efadea18be64e3b0f0839add3cadf4a1757fcc40/demos/blockfactory/factory.js#L1145)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> the updateGenerator code  injects the code into the generator preview text area whereas I just want it 
> called at the end of it, but I can move it out so that I can reuse the updateGenerator function.
> 
> does that sound good?
> </details>
> created getGeneratorStub function that is shared by export  & factory.js

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/7#-:-KNJdMY4bPOe5wkOoTN5:1417088721)_

**Pull request merged**
