### PR TITLE
Block Library: Create New Block Button

### PR DESCRIPTION
**Pull request by quachtina96**
If the user wants a fresh slate for creating a new block, they can press this button to load the starter workspace (with factory_base block loaded)  you get when you first load the page. 
screen shot 2016-08-03 at 2 45 10 pm

factory.js: create showStarterBlock function
block_factory_expansion.js: add button handler for creating a new block
index.html: add new button

---

This change is [Reviewable](https://reviewable.io/reviews/quachtina96/blockly/20)

### CODE REVIEW

**Comment by quachtina96** [comment]
@evd2014 @vicng @picklesrus 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/20#-:-KOHm46XbP7v-ydDoV-T:-1156168519)_

**Comment by picklesrus** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[demos/blockfactory/factory.js, line 900 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/20#-KOHo7wGA0jZs-s97AeI:-KOHo7wGA0jZs-s97AeJ:632827904) ([raw file](https://github.com/quachtina96/blockly/blob/18621a4ac8cae66a461610e7b7d8953ec7e00cf8/demos/blockfactory/factory.js#L900)):_

> ``` JavaScript
>  */
> BlockFactory.show = function(elementID) {
>   document.getElementById(elementID).style.display = 'inline';
> ```

Looks like maybe a bad merge?  I thought you needed this to be block.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/20)_

**Comment by quachtina96** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[demos/blockfactory/factory.js, line 900 [r1]](https://reviewable.io:443/reviews/quachtina96/blockly/20#-KOHo7wGA0jZs-s97AeI:-KOHvrCsykRILP2ll7WM:1384023607) ([raw file](https://github.com/quachtina96/blockly/blob/18621a4ac8cae66a461610e7b7d8953ec7e00cf8/demos/blockfactory/factory.js#L900)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> Looks like maybe a bad merge?  I thought you needed this to be block.
> </details>
> I re-made the change in this pull request so that it will get merged into master.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/20)_

**Comment by vicng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[demos/blockfactory/block_factory_expansion.js, line 1 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/20#-KOHxO7O7oQ3uhyMM7Dy:-KOHxO7O7oQ3uhyMM7Dz:1174747444) ([raw file](https://github.com/quachtina96/blockly/blob/52a233a2440fb2d70b7162af50d59a3ee292788a/demos/blockfactory/block_factory_expansion.js#L1)):_

> ``` JavaScript
> /**
> ```

Old code?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/20)_

**Comment by quachtina96** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[demos/blockfactory/block_factory_expansion.js, line 1 [r2]](https://reviewable.io:443/reviews/quachtina96/blockly/20#-KOHxO7O7oQ3uhyMM7Dy:-KOI-s48XJ1hUnGW_dKk:-1981669666) ([raw file](https://github.com/quachtina96/blockly/blob/52a233a2440fb2d70b7162af50d59a3ee292788a/demos/blockfactory/block_factory_expansion.js#L1)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Old code?
> </details>
> just rebased! and deleted this file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/20)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/20#-:-KOImaY43ogJTBWlsRGC:1417088721)_

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/quachtina96/blockly/20#-:-KOLJc3DPCoMSJ2KVTcz:1417088721)_

**Pull request merged**
